server:
  port: 8081

#database 설정
spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://k4c104.p.ssafy.io:3306/test1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy104
    password: ssafyill@sa

  jpa:
    show-sql: true
    hibernate:
      # create : drop + create, create-drop : drop + create + drop, update : compare > diff > update, validate : compare > diff > end application
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true

# openapi 3.0 설정
springdoc:
  version: "@project.version@"
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  # controller path 등록
  paths-to-match:
    - /api/v1/**
    - /transaction/**


