server:
  port: 8001

#database 설정
spring:
  application:
    name: condolenceserver
  datasource:
    url: jdbc:mysql://k4c104.p.ssafy.io:3306/test1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy104
    password: ssafyill@sa
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true

# openapi 3.0 설정
springdoc:
  version: "@project.version@"
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  # controller path 등록
  paths-to-match:
    - /api/v1/**
    - /dead/**
    - /guest/**
    - /relation/**
    - /condolence/**

#S3
cloud:
  aws:
    credentials:
      accessKey: AKIAXS7MUVFIJETRS5PQ
      secretKey: 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
    s3:
      bucket: grium
    region:
      static: ap-northeast-2
    stack:
      auto: false



